import { randomUUID } from 'crypto';
import { minioClient } from '../config/minio';
import { env } from '../config/env';

interface GenerateImageParams {
  prompt: string;
  style?: string;
  aspectRatio?: '1:1' | '9:16' | '4:5';
}

interface GenerateImageResult {
  imageUrl: string;
  minioKey: string;
}

function enrichPrompt(prompt: string, style?: string): string {
  const base = 'Professional social media post, high quality, vibrant colors, modern design';
  return style ? `${base}, ${style} style, ${prompt}` : `${base}, ${prompt}`;
}

// Map aspect ratios to Gemini-supported values
function mapAspectRatio(ratio?: string): string {
  const map: Record<string, string> = {
    '1:1': '1:1',
    '9:16': '9:16',
    '4:5': '3:4', // closest supported by Gemini
  };
  return map[ratio || '1:1'] || '1:1';
}

export async function generateImage(params: GenerateImageParams): Promise<GenerateImageResult> {
  const enrichedPrompt = enrichPrompt(params.prompt, params.style);
  const model = 'gemini-3.1-flash-image-preview';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${env.NANO_BANANA_API_KEY}`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [{ parts: [{ text: `Generate an image: ${enrichedPrompt}` }] }],
      generationConfig: {
        responseModalities: ['TEXT', 'IMAGE'],
        imageConfig: {
          aspectRatio: mapAspectRatio(params.aspectRatio),
        },
      },
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Gemini API error ${response.status}: ${errorText}`);
  }

  const data = (await response.json()) as any;

  // Find the image part in the response
  const candidates = data.candidates;
  if (!candidates || candidates.length === 0) {
    throw new Error('No candidates returned from Gemini API');
  }

  const parts = candidates[0].content?.parts || [];
  const imagePart = parts.find((p: any) => p.inlineData?.mimeType?.startsWith('image/'));

  if (!imagePart) {
    throw new Error('No image generated by Gemini API');
  }

  const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');

  if (imageBuffer.length < 1000) {
    throw new Error('Generated image too small, possibly invalid');
  }

  const ext = imagePart.inlineData.mimeType === 'image/jpeg' ? 'jpg' : 'png';
  const contentType = imagePart.inlineData.mimeType;
  const key = `posts/${Date.now()}-${randomUUID()}.${ext}`;
  await minioClient.putObject(env.MINIO_BUCKET, key, imageBuffer, imageBuffer.length, {
    'Content-Type': contentType,
  });

  const imageUrl = `${env.MINIO_PUBLIC_URL}/${env.MINIO_BUCKET}/${key}`;
  return { imageUrl, minioKey: key };
}
